config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :posts
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :spot_name, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
  
  mount_uploader :icon, ImageUploader

  def self.guest
    find_or_create_by!(name: "ゲストユーザー", email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[edit update destroy]

  def index
    @posts = Post.order(:created_at)
  end

  def new
    @post = Post.new
  end

  def create
    post = current_user.posts.create!(post_params)
    redirect_to post
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
  end

  def update
    @post.update!(post_params)
    redirect_to @post
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy!
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:spot_name, :content)
  end

  def set_post
    @post = current_user.posts.find(params[:id])
    redirect_to root_path, alert: "権限がありません" if @post.nil?
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: :destroy

  def ensure_normal_user
    if resource.email == "guest@example.com"
      redirect_to root_path, alert: "ゲストユーザーは削除できません。"
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    # ゲストアカウントでログイン
    sign_in User.guest
    # トップページへリダイレクト
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <%# ログイン時 %>
  <%= link_to "一覧ページ", root_path %>
  <%= link_to "新規投稿ページ", new_post_path %>
  <%= link_to "アカウント編集", edit_user_registration_path %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } %>
<% else %>
  <%# 非ログイン時 %>
  <%= link_to "新規登録", new_user_registration_path %>
  <%= link_to "ログイン", new_user_session_path %>
  <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, method: :post %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FishingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>
  <p>
    <%= form.label :spot_name %>
  </p>
  <p>
    <%= form.text_field :spot_name, required: true %>
  </p>
  <p>
    <%= form.label :content %>
  </p>
    <%= form.text_area :content, required: true %>
  <p>
    <%= form.submit "投稿" %>
  </p>
<% end %>

app/views/posts/_post.html.erb
<div>
  <p>【名前】 <%= post.user.name %></p>
  <p>【釣り場】 <%= post.spot_name %></p>
  <p>
    <% if current_user.id == post.user_id %>
      <%= link_to "編集", edit_post_path(post) %>
      <%= link_to "削除", post_path(post), method: :delete, data: { confirm: "削除しますか？" } %>
    <% end %>
  </p>
</div>
<hr>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
post = Post.find(params[:id])
    post.destroy!
    redirect_to root_path

app/views/posts/edit.html.erb
<h1>編集</h1>
<%= render "form" %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<%= render @posts %>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= render "form" %>

app/views/posts/show.html.erb
<h1>投稿詳細</h1>
<p>【名前】 <%= @post.user.name %></p>
<p>【釣り場】 <%= @post.spot_name %></p>
<p>【釣果内容】 <%= @post.content %></p>
<% if current_user.id == @post.user_id %>
  <p>
    <%= link_to "編集", edit_post_path(@post) %>
    <%= link_to "削除", post_path(@post), method: :delete, data: { confirm: "削除しますか？" } %>
  </p>
<% end %>
<p><%= link_to "投稿一覧へ", posts_path %></p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>